In [2]:
%gui qt
import napari
import pandas as pd
import numpy as np
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
from shapely.geometry import Polygon, Point

## Make a napari viewer...

In [3]:
v = napari.Viewer()

## Load cell x gene data from 1 dataset

In [4]:
all_cells = pd.read_csv("/Users/brian/Downloads/DARTFISH_CellxGene_Mm_20190513_T.csv")



### Add the cells as points, double-plotting cells with high Rorb, Cux2 if available

In [5]:
cells = v.add_points(all_cells[["x","y"]], symbol='o', name = "all", opacity = 0.8, blending = "translucent")
colorlist = ["magenta", "green","yellow","cyan", "blue", "orange"]
for ii, gene_to_plot in enumerate(["Cux2", "Atp1a3" , "Vxn", "Pcp4" , "Fezf2" , "Rorb" , "Gm11549"]):

    if gene_to_plot in all_cells:
        cux2condition = all_cells[gene_to_plot]>0.5*all_cells[gene_to_plot].median()
        cux2cells = v.add_points(all_cells[cux2condition][["x","y"]], symbol='disc',
                                 name = gene_to_plot+"+",edge_color= "black", size = 50,
                                 face_color= colorlist[ ii % len(colorlist)] , blending = "translucent", opacity = 0.3)


### annotate the layers in that viewer in a single `shapes` layer
#### Naming/order Convention:
0. outline of entire column as rectangle
1. Layer 1
1. Layer 2/3
2. Layer 4
3. Layer 5
4. Layer 6
5. single line segment, pointing from pia to white matter 

#### annotate the layer locations in a list

In [6]:
v.layers

[<Points layer 'all' at 0x12ecb0f10>,
 <Points layer 'Atp1a3+' at 0x12ecfd710>,
 <Points layer 'Pcp4+' at 0x10d92d4d0>,
 <Points layer 'Fezf2+' at 0x12b373bd0>,
 <Points layer 'Rorb+' at 0x12b3d38d0>,
 <Points layer 'Gm11549+' at 0x12b430e90>,
 <Shapes layer 'Shapes' at 0x12b523750>]

In [66]:
is_in_layer = {ii:[Polygon(p).intersects(Point(a))  for a  in v.layers[0].data] for ii,p in enumerate(v.layers[-1].data[:-2])}

In [ ]:
# ok:
# 1. make a couple functions to do this
#.  #. do a spatially partitioned search based on bounding box of polygon
# 2. throw annotation into separate vector matched to point cloud
#. 

In [67]:
is_in_layer

{0: [False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False

In [17]:
annotations = v.layers[4]

In [21]:
annotations.data

[array([[  322.69221525, 10409.33143621],
        [10023.76221747,  4247.2783876 ],
        [12605.16281892,  8285.92126406],
        [ 3112.27028456, 14864.32924839],
        [ 3112.27028456, 14864.32924839]]),
 array([[ 3195.5412717 , 14781.05826125],
        [  405.9632024 , 10492.60242336],
        [ 1696.66350312,  9659.89255192],
        [ 2529.37337456, 11533.48976265],
        [ 3445.35423313, 13074.00302481],
        [ 4194.79311743, 14073.25487053],
        [ 4194.79311743, 14073.25487053]]),
 array([[ 4278.06410457, 13948.34838981],
        [ 3903.34466242, 13573.62894767],
        [ 2820.82182956, 12033.11568551],
        [ 2196.28942598, 10784.05087836],
        [ 1655.02800955,  9618.25705835],
        [ 4028.25114314,  8161.01478334],
        [ 4611.14805314,  9493.35057764],
        [ 5776.94187315, 11491.85426908],
        [ 6526.38075744, 12366.19963409],
        [ 6526.38075744, 12366.19963409]]),
 array([[ 6568.01625101, 12366.19963409],
        [ 5860.21286029, 115

In [30]:
is_in_layer = {ii:[Polygon(p).intersects(Point(a))  for a  in v.layers[0].data] for ii,p in enumerate(annotations.data)}

In [68]:
v.add_points(all_cells[is_in_layer[1]][["x","y"]], symbol='o', size = 30)

<Points layer 'Points' at 0x133fe4390>

In [28]:
for ii,p in enumerate(annotations.data):
    print(p)

[[  322.69221525 10409.33143621]
 [10023.76221747  4247.2783876 ]
 [12605.16281892  8285.92126406]
 [ 3112.27028456 14864.32924839]
 [ 3112.27028456 14864.32924839]]
[[ 3195.5412717  14781.05826125]
 [  405.9632024  10492.60242336]
 [ 1696.66350312  9659.89255192]
 [ 2529.37337456 11533.48976265]
 [ 3445.35423313 13074.00302481]
 [ 4194.79311743 14073.25487053]
 [ 4194.79311743 14073.25487053]]
[[ 4278.06410457 13948.34838981]
 [ 3903.34466242 13573.62894767]
 [ 2820.82182956 12033.11568551]
 [ 2196.28942598 10784.05087836]
 [ 1655.02800955  9618.25705835]
 [ 4028.25114314  8161.01478334]
 [ 4611.14805314  9493.35057764]
 [ 5776.94187315 11491.85426908]
 [ 6526.38075744 12366.19963409]
 [ 6526.38075744 12366.19963409]]
[[ 6568.01625101 12366.19963409]
 [ 5860.21286029 11575.12525622]
 [ 4736.05453386  9659.89255192]
 [ 3944.98015599  8077.7437962 ]
 [ 5901.84835387  6911.94997619]
 [ 7941.98753888  9951.34100692]
 [ 8649.7909296  10992.22834622]
 [ 8649.7909296  10992.22834622]]
[[ 869

In [69]:
# depth coordinate calculation